# Generated by Django 2.2.5 on 2019-10-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20, verbose_name='编号')),
                ('url', models.CharField(max_length=30, verbose_name='地址')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('desc', models.CharField(max_length=20, verbose_name='导演')),
                ('grade', models.CharField(max_length=5, verbose_name='评分')),
            ],
        ),
    ]
